package ua.weather.app;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.util.List;

/**
 * list of city codes (class was generated by jsonschema2pojo )
 */
class IpmaCityCodes {

    @SerializedName("owner")
    @Expose
    private String owner;
    @SerializedName("country")
    @Expose
    private String country;
    @SerializedName("data")
    @Expose
    private List<CityCodes> data = null;

    public String getOwner() {
    return owner;
    }

    public void setOwner(String owner) {
    this.owner = owner;
    }

    public String getCountry() {
    return country;
    }

    public void setCountry(String country) {
    this.country = country;
    }

    public List<CityCodes> getData() {
    return data;
    }

    public void setData(List<CityCodes> data) {
    this.data = data;
    }

}

/**
 * the data point with the different codes corresponding to different cities
 */
class CityCodes {

    @SerializedName("idRegiao")
    @Expose
    private Integer idRegiao;
    @SerializedName("idAreaAviso")
    @Expose
    private String idAreaAviso;
    @SerializedName("idConcelho")
    @Expose
    private Integer idConcelho;
    @SerializedName("globalIdLocal")
    @Expose
    private Integer globalIdLocal;
    @SerializedName("latitude")
    @Expose
    private String latitude;
    @SerializedName("idDistrito")
    @Expose
    private Integer idDistrito;
    @SerializedName("local")
    @Expose
    private String local;
    @SerializedName("longitude")
    @Expose
    private String longitude;
    
    public Integer getIdRegiao() {
    return idRegiao;
    }
    
    public void setIdRegiao(Integer idRegiao) {
    this.idRegiao = idRegiao;
    }
    
    public String getIdAreaAviso() {
    return idAreaAviso;
    }
    
    public void setIdAreaAviso(String idAreaAviso) {
    this.idAreaAviso = idAreaAviso;
    }
    
    public Integer getIdConcelho() {
    return idConcelho;
    }
    
    public void setIdConcelho(Integer idConcelho) {
    this.idConcelho = idConcelho;
    }
    
    public Integer getGlobalIdLocal() {
    return globalIdLocal;
    }
    
    public void setGlobalIdLocal(Integer globalIdLocal) {
    this.globalIdLocal = globalIdLocal;
    }
    
    public String getLatitude() {
    return latitude;
    }
    
    public void setLatitude(String latitude) {
    this.latitude = latitude;
    }
    
    public Integer getIdDistrito() {
    return idDistrito;
    }
    
    public void setIdDistrito(Integer idDistrito) {
    this.idDistrito = idDistrito;
    }
    
    public String getLocal() {
    return local;
    }
    
    public void setLocal(String local) {
    this.local = local;
    }
    
    public String getLongitude() {
    return longitude;
    }
    
    public void setLongitude(String longitude) {
    this.longitude = longitude;
    }
    
}
